//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_de_jogos.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quiz_de_jogos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _00000013583_300x300 {
            get {
                object obj = ResourceManager.GetObject("00000013583_300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_DCI_GdMJ6nHXneSsyw3mKQ {
            get {
                object obj = ResourceManager.GetObject("1_DCI_GdMJ6nHXneSsyw3mKQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_DCI_GdMJ6nHXneSsyw3mKQ1 {
            get {
                object obj = ResourceManager.GetObject("1_DCI_GdMJ6nHXneSsyw3mKQ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1340566 {
            get {
                object obj = ResourceManager.GetObject("1340566", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1e177bbcd1aad6e21d3c21c81382d35a {
            get {
                object obj = ResourceManager.GetObject("1e177bbcd1aad6e21d3c21c81382d35a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2013bf037e28c82554874b16d0248c21 {
            get {
                object obj = ResourceManager.GetObject("2013bf037e28c82554874b16d0248c21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017GettyImages_snoop_dogg_tupac_hall_of_fame_920x584 {
            get {
                object obj = ResourceManager.GetObject("2017GettyImages-snoop-dogg-tupac-hall-of-fame-920x584", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017GettyImages_snoop_dogg_tupac_hall_of_fame_920x5841 {
            get {
                object obj = ResourceManager.GetObject("2017GettyImages-snoop-dogg-tupac-hall-of-fame-920x5841", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_uapzfp_400x400 {
            get {
                object obj = ResourceManager.GetObject("4_uapzfp_400x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4cfa27c8dcfd8636337d60e6c1f4a7cb693a9bf8r1_380_380v2_00 {
            get {
                object obj = ResourceManager.GetObject("4cfa27c8dcfd8636337d60e6c1f4a7cb693a9bf8r1-380-380v2_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51688b0a14f59a34fee35828408b6154 {
            get {
                object obj = ResourceManager.GetObject("51688b0a14f59a34fee35828408b6154", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51688b0a14f59a34fee35828408b6154__1_ {
            get {
                object obj = ResourceManager.GetObject("51688b0a14f59a34fee35828408b6154 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _54_1_e1574015255159 {
            get {
                object obj = ResourceManager.GetObject("54-1-e1574015255159", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5550723fe973da99e0e3b6237daf77562144e3bd_hq {
            get {
                object obj = ResourceManager.GetObject("5550723fe973da99e0e3b6237daf77562144e3bd_hq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _778825be381be66db27d56ba533034ea {
            get {
                object obj = ResourceManager.GetObject("778825be381be66db27d56ba533034ea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7set2015___o_dublador_fabio_lucindo_vai_deixar_a_serie_pokemon_apos_18_temporadas_como_a_voz_do_protagonista_ash_1441671292696_300x300 {
            get {
                object obj = ResourceManager.GetObject("7set2015---o-dublador-fabio-lucindo-vai-deixar-a-serie-pokemon-apos-18-temporadas" +
                        "-como-a-voz-do-protagonista-ash-1441671292696_300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81bO8z8p1eL__SX466_ {
            get {
                object obj = ResourceManager.GetObject("81bO8z8p1eL._SX466_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c1545aa37752ad0883ed6cae3586e10 {
            get {
                object obj = ResourceManager.GetObject("8c1545aa37752ad0883ed6cae3586e10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c20f1e523629b0dff72fd4cf809ebd4dd1f285a_hq {
            get {
                object obj = ResourceManager.GetObject("8c20f1e523629b0dff72fd4cf809ebd4dd1f285a_hq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c20f1e523629b0dff72fd4cf809ebd4dd1f285a_hq1 {
            get {
                object obj = ResourceManager.GetObject("8c20f1e523629b0dff72fd4cf809ebd4dd1f285a_hq1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aaa {
            get {
                object obj = ResourceManager.GetObject("aaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adrianalimadonnakaran_475x3861 {
            get {
                object obj = ResourceManager.GetObject("adrianalimadonnakaran-475x3861", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buzzfeed_quiz {
            get {
                object obj = ResourceManager.GetObject("buzzfeed-quiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c_net_logo {
            get {
                object obj = ResourceManager.GetObject("c_net_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap candice_swanepoel {
            get {
                object obj = ResourceManager.GetObject("candice-swanepoel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Capturar {
            get {
                object obj = ResourceManager.GetObject("Capturar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Charizard {
            get {
                object obj = ResourceManager.GetObject("Charizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dos_Reis_Carvalho_Eduardo_Genoa_CFC_v_ACF_FaZ8xYSYXMDl {
            get {
                object obj = ResourceManager.GetObject("Dos+Reis+Carvalho+Eduardo+Genoa+CFC+v+ACF+FaZ8xYSYXMDl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap durant_serie_espn {
            get {
                object obj = ResourceManager.GetObject("durant_serie_espn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gettyimages_131964832_612x612 {
            get {
                object obj = ResourceManager.GetObject("gettyimages-131964832-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Golden_State_Warriors {
            get {
                object obj = ResourceManager.GetObject("Golden_State_Warriors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haste_riven {
            get {
                object obj = ResourceManager.GetObject("haste-riven", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20190109_120003 {
            get {
                object obj = ResourceManager.GetObject("IMG_20190109_120003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20190109_120003__1_ {
            get {
                object obj = ResourceManager.GetObject("IMG_20190109_120003 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap james_brown_06022019130430288 {
            get {
                object obj = ResourceManager.GetObject("james-brown-06022019130430288", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large_1516818701_4ba1eb7d2a35889b0ac64b73d4e71af6 {
            get {
                object obj = ResourceManager.GetObject("large-1516818701-4ba1eb7d2a35889b0ac64b73d4e71af6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_javascript_png_free_vector_logo_javascript_300 {
            get {
                object obj = ResourceManager.GetObject("logo-javascript-png-free-vector-logo-javascript-300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Luffy_one_piece_10339026_300_300 {
            get {
                object obj = ResourceManager.GetObject("Luffy-one-piece-10339026-300-300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap majin_boo_1 {
            get {
                object obj = ResourceManager.GetObject("majin boo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marega_qd_300x300 {
            get {
                object obj = ResourceManager.GetObject("marega-qd-300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mj {
            get {
                object obj = ResourceManager.GetObject("mj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhaça {
            get {
                object obj = ResourceManager.GetObject("nhaça", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ricardo {
            get {
                object obj = ResourceManager.GetObject("ricardo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Riolu_Anime_the_official_riolu_fan_club_39925792_220_228 {
            get {
                object obj = ResourceManager.GetObject("Riolu-Anime-the-official-riolu-fan-club-39925792-220-228", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap riven_png_image_with_transparent_background_toppng_riven_png_850_502 {
            get {
                object obj = ResourceManager.GetObject("riven-png-image-with-transparent-background-toppng-riven-png-850_502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rkau0MBR_400x400 {
            get {
                object obj = ResourceManager.GetObject("rkau0MBR_400x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rs_634x1024_190522154219_634_billie_eilish_cm_52219 {
            get {
                object obj = ResourceManager.GetObject("rs_634x1024-190522154219-634-billie-eilish.cm.52219", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sem_Título {
            get {
                object obj = ResourceManager.GetObject("Sem Título", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Snoop_Dogg_Smoking_Weed_300x201 {
            get {
                object obj = ResourceManager.GetObject("Snoop-Dogg-Smoking-Weed-300x201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transferir {
            get {
                object obj = ResourceManager.GetObject("transferir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tupac {
            get {
                object obj = ResourceManager.GetObject("tupac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
